title = "Ownership (Part 2)"
slides = "09_ownership_p2"

[homework]
name = "Ownership Quiz"

[homework_alt]
name = "Project Checkpoint 1"

[[extras]]
title = "Aquascope: Visualizing Rust Permissions"
url = "https://cel.cs.brown.edu/aquascope/"
