#!/usr/bin/env bash

# Copy student's submission into the test crate.
cp -r /autograder/submission/src/. /autograder/source/getownedlab/src

# Run the test suite.
cd /autograder/source
python3 run_tests.py
